# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ullas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='slug',
        ),
        migrations.AlterField(
            model_name='box',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='ullas.Catalog', verbose_name='Tillhör katalog'),
        ),
        migrations.AlterField(
            model_name='card',
            name='box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='ullas.Box', verbose_name='kort'),
        ),
    ]
