# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 15:51
from __future__ import unicode_literals

from django.db import migrations
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ullas', '0002_auto_20161231_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='catalog',
        ),
        migrations.AddField(
            model_name='card',
            name='search_index',
            field=djorm_pgfulltext.fields.VectorField(db_index=True, default='', editable=False, null=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
