# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djorm_pgfulltext.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(help_text='Filkatalog på disk där denna lådas filer ligger', max_length=255, unique=True, verbose_name='Katalognamn')),
                ('sequence_number', models.IntegerField(db_index=True)),
                ('label', models.CharField(db_index=True, max_length=255, verbose_name='Etikett')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lådor',
                'abstract': False,
                'ordering': ['sequence_number'],
                'verbose_name': 'Låda',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Rubriken som visas överst på en kortsida', max_length=255, verbose_name='Kortnamn')),
                ('filename', models.CharField(db_index=True, help_text='Filnamnet för bildfilen', max_length=255, verbose_name='Filnamn')),
                ('filename_back', models.CharField(db_index=True, help_text='Filnamnet för bildfilen av baksidan', max_length=255, verbose_name='Filnamn baksida')),
                ('ocr_text', models.TextField(blank=True, help_text='Automatiskt OCR-tolkad text från kortet.')),
                ('ocr_text_back', models.TextField(blank=True, help_text='Automatiskt OCR-tolkad text från kortets baksida.')),
                ('letter', models.CharField(blank=True, db_index=True, help_text='Anges för första kortet för att dela upp katalogen alfabetiskt.', max_length=1, null=True, verbose_name='Indexbokstav')),
                ('sequence_number', models.IntegerField(db_index=True, verbose_name='Sekvensnummer i låda')),
                ('catalog_sequence_number', models.IntegerField(blank=True, help_text='Globalt katalognummer som anger kortets plats i katalogen. Används även som identifierare.', null=True, verbose_name='Kortnummer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, help_text='Visas ej för besökare.', null=True, verbose_name='Intern kommentar')),
                ('search_index', djorm_pgfulltext.fields.VectorField(db_index=True, default='', editable=False, null=True, serialize=False)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='hsnominal.Box', verbose_name='kort')),
            ],
            options={
                'verbose_name_plural': 'Kort',
                'abstract': False,
                'ordering': ['catalog_sequence_number'],
                'verbose_name': 'Kort',
            },
        ),
    ]
